# Generated by Django 2.2 on 2019-07-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='house_model',
            field=models.CharField(default='', max_length=200),
        ),
    ]
